---
- hosts: rails
  remote_user: root
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Add deploy user
      user:
        name: deploy
        shell: /bin/bash
    - name: Add SSH key to server for deploy user
      authorized_key:
        user: deploy
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuhuF+VOxKIRVgDFzYPbpVVVofqvMJq6CUfRiPy/NTJIQu6s8Nia3aEQdkDcbELoeJOqfZ/TeUv9ObrUIhNcEqN8D9M4Hm0iglqVMcVfsnHGZfMRu56ikwN9i1b4nIM+jgZhGCMREZlbbFcJr9f5BetdpdeGAtrHNAPusD2O2hcSdQwcUK5fXANn8IULelkqxjbl7wz1TO5Ejeh3zJVfDW6fN9nxUIZvNmVeUKcio5OAbIU24NRR/epzVmMkTwLI3NZq8wQOSNWUEdV3akdxKSoWbTmBhWqgYJFZOFLfnj3cbbT/cDAfjLnn27m6HfDMyrmchANGGL/znYJ9Ga4NnKo7hOnAFeCqwnpBpEJWxhf9UhrmRj6OMxI59OWlGd+8grh1lykAw9SJHwRM0JeneBhbkqvcwA9bH707MBxt3XL6GYBrNEwWTPRs26dDHmLsHQ9K5wh5QGa3Fawg5rt6XunWeC9ARrPx/Lu7twzjjkne3K/gredqhB0wJ/TjIHQiyw2NozbWzD1MS0ZmzNtGgUHFW2O6eOE+oRmfQcraHZxyAkIJZVSSry7TRIseTJEVFC0LPxKlqco3I5vRxRpi9EAwNR/6xkIrgmo000vLssKrYmYbRiSRAyXOTigYEJ2wh6qK911XKbv+i84wCqnWqq1e3+xGF1raAJ6oajGGRtxQ== radoslaw.stolarski@polcode.net"
    - name: Install Ruby dependencies
      apt:
        pkg:
          - gcc
          - autoconf
          - bison
          - build-essential
          - libssl-dev
          - libyaml-dev
          - libreadline6-dev
          - zlib1g-dev
          - libncurses5-dev
          - libffi-dev
          - libgdbm-dev
          - sqlite3
          - libsqlite3-dev
          - nodejs
          - libgdbm5
        state: present
    - name: Download ruby-install
      become: no
      get_url:
        url: https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
        dest: /home/ubuntu/ruby-install-0.7.0.tar.gz
    - name: Extract ruby-install tarball 
      become: no
      unarchive:
        src: /home/ubuntu/ruby-install-0.7.0.tar.gz
        dest: /home/ubuntu
        creates: /home/ubuntu/ruby-install-0.7.0
        remote_src: yes
    - name: Install ruby-install
      make:
        chdir: /home/ubuntu/ruby-install-0.7.0
        target: install
    - name: Install ruby
      become_user: deploy
      command: /usr/local/bin/ruby-install --no-install-deps ruby 2.5.0
      args:
        creates: /home/deploy/.rubies/ruby-2.5.0
    - name: Download chruby
      become: no
      get_url:
        url: https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
        dest: /home/ubuntu/chruby-0.3.9.tar.gz
    - name: Extract chruby tarball
      become: no
      unarchive:
        src: /home/ubuntu/chruby-0.3.9.tar.gz
        dest: /home/ubuntu
        creates: /home/ubuntu/chruby-0.3.9
        remote_src: yes
    - name: Install chruby
      make:
        chdir: /home/ubuntu/chruby-0.3.9
        target: install
    - name: Load chruby for deploy user
      lineinfile:
        path: /home/deploy/.bashrc
        regexp: 'chruby.sh$'
        line: 'source /usr/local/share/chruby/chruby.sh'
        insertbefore: BOF
    - name: Set ruby version for deploy user
      lineinfile:
        path: /home/deploy/.profile
        regexp: '^chruby'
        line: 'chruby ruby-2.5.0'
    - name: Install bundler
      become_user: deploy
      command: 'chruby-exec ruby-2.5.0 -- gem install bundler'
      args:
        creates: /home/deploy/.gem/ruby/2.5.0/bin/bundle
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    - name: Upload nginx config
      copy:
        src: nginx_config
        dest: /etc/nginx/sites-available/rails
      notify:
        - Restart nginx
    - name: Disable default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Restart nginx
    - name: Enable nginx config
      file:
        src: /etc/nginx/sites-available/rails
        dest: /etc/nginx/sites-enabled/rails
        state: link
      notify:
        - Restart nginx
  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted


    

