---
# tasks file for ansible/roles/add_deploy_user
- name: Add deploy user
  user:
    name: deploy
    shell: /bin/bash
- name: Add SSH key to server for deploy user
  authorized_key:
    user: deploy
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuhuF+VOxKIRVgDFzYPbpVVVofqvMJq6CUfRiPy/NTJIQu6s8Nia3aEQdkDcbELoeJOqfZ/TeUv9ObrUIhNcEqN8D9M4Hm0iglqVMcVfsnHGZfMRu56ikwN9i1b4nIM+jgZhGCMREZlbbFcJr9f5BetdpdeGAtrHNAPusD2O2hcSdQwcUK5fXANn8IULelkqxjbl7wz1TO5Ejeh3zJVfDW6fN9nxUIZvNmVeUKcio5OAbIU24NRR/epzVmMkTwLI3NZq8wQOSNWUEdV3akdxKSoWbTmBhWqgYJFZOFLfnj3cbbT/cDAfjLnn27m6HfDMyrmchANGGL/znYJ9Ga4NnKo7hOnAFeCqwnpBpEJWxhf9UhrmRj6OMxI59OWlGd+8grh1lykAw9SJHwRM0JeneBhbkqvcwA9bH707MBxt3XL6GYBrNEwWTPRs26dDHmLsHQ9K5wh5QGa3Fawg5rt6XunWeC9ARrPx/Lu7twzjjkne3K/gredqhB0wJ/TjIHQiyw2NozbWzD1MS0ZmzNtGgUHFW2O6eOE+oRmfQcraHZxyAkIJZVSSry7TRIseTJEVFC0LPxKlqco3I5vRxRpi9EAwNR/6xkIrgmo000vLssKrYmYbRiSRAyXOTigYEJ2wh6qK911XKbv+i84wCqnWqq1e3+xGF1raAJ6oajGGRtxQ== radoslaw.stolarski@polcode.net"
