---
# tasks file for ansible/roles/add_deploy_user
- name: Add deploy user
  user:
    name: deploy
    shell: /bin/bash
- name: Add SSH key to server for deploy user
  authorized_key:
    user: deploy
    key: "{{ vault_ssh_public_key }}"
